name: 🐛 Bug Report
description: Report a bug or unexpected behavior in Eterna-Core
title: "[BUG] "
labels: [bug]
body:
  - type: input
    id: version
    attributes:
      label: Eterna-Core Version
      placeholder: e.g. 1.0.0-beta
  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Describe the issue in detail and steps to reproduce it.
  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      placeholder: Paste any relevant log output or screenshots
